version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile  # Ensure correct file name
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/mydb  # Use service name, not localhost

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db:
    build:
      context: ./packages/db
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/mydb  # Fix database connection
    volumes:
      - .:/app
    command: ["npx", "prisma", "migrate", "deploy"]

volumes:
  postgres_data:
